# Generated by Django 3.2.8 on 2022-09-28 14:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_biographies_book'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Book',
            new_name='Project',
        ),
    ]
