# Generated by Django 3.2.8 on 2022-09-28 15:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_rename_book_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Biographies',
            new_name='TODO',
        ),
        migrations.AddField(
            model_name='project',
            name='url',
            field=models.URLField(default=''),
        ),
        migrations.AlterField(
            model_name='project',
            name='id',
            field=models.AutoField(primary_key=True, serialize=False),
        ),
        migrations.AlterField(
            model_name='todo',
            name='users',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='users.project'),
        ),
    ]
